coverage_service: coveralls
xcodeproj: Example/SnapLayout.xcodeproj
workspace: Example/SnapLayout.xcworkspace
source_directory: Pod/Classes
scheme: SnapLayout_ExampleTests
binary_basename: SnapLayout
