# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

sudo: false
osx_image: xcode10.3
language: swift
podfile: Example/Podfile
before_install:
  - gem install slather --no-document
  - gem install cocoapods
  # Travis sometimes fails. Workaround below. Current Issue: https://github.com/travis-ci/travis-ci/issues/6675
  - gem install simctl --no-document --quiet
#  - ruby -rsimctl -e 'SimCtl.warmup("iPhone X", "iOS 11.0", 300)'
#  - gem install xcpretty (prints log in pretty format)
  - pod install --project-directory=Example

script:
  # xcpretty will sometimes cause CI to fail: https://github.com/bitrise-io/bitrise.io/issues/5
    - set -o pipefail && xcodebuild -workspace Example/SnapLayout.xcworkspace -scheme SnapLayout_ExampleTests -destination 'platform=iOS Simulator,name=iPhone 5s,OS=12.0' build test # | xcpretty -c
    - pod lib lint --allow-warnings # warning states variable should be immutable but the variable does change. Seems to be lint issue

after_success: slather
notifications:
  email: false
