# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

sudo: false
osx_image: xcode8
language: swift
podfile: Example/Podfile
before_install:
  - gem install slather --no-ri --no-rdoc
  - gem install cocoapods
#  - gem install xcpretty (prints log in pretty format)
  - pod install --project-directory=Example

script:
  # xcpretty will sometimes cause CI to fail: https://github.com/bitrise-io/bitrise.io/issues/5
    - set -o pipefail && xcodebuild -workspace Example/SnapLayout.xcworkspace -scheme Pods-SnapLayout_ExampleTests -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' build test # | xcpretty -c
    - pod lib lint --allow-warnings # warning states variable should be immutable but the variable does change. Seems to be lint issue

after_success: slather